version: 3

tasks:
  install:
    aliases: [ "i" ]
    cmds:
      - bun install

  run:
    aliases: [ "r" ]
    cmds:
#      - yarn start
      - bun run start

  deploy:
    cmds:
      - DEPLOYMENT_BRANCH=gh-pages USE_SSH=true yarn deploy

