/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    WDownload: typeof import('./src/components/WDownload.vue')['default']
    WHelp: typeof import('./src/components/WHelp.vue')['default']
    WLicense: typeof import('./src/components/WLicense.vue')['default']
    WPricing: typeof import('./src/components/WPricing.vue')['default']
    WScreenshots: typeof import('./src/components/WScreenshots.vue')['default']
  }
}
