version: "3"

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing


################################################################################################

tasks:
  default:
    cmds:
      - echo "hello world"

  install:
    aliases: [ "i" ]
    cmds:
      - bun install

  add:
    aliases: [ "a" ]
    cmds:
      - bun add -D vitepress
      - bun add -D open-cli
      - bun add -D @lunariajs/core
      - bun add -D markdown-it-mathjax3

  run:
    aliases: [ "r" ]
    cmds:
      - bun run dev

  build:
    aliases: [ "b" ]
    cmds:
      - bun run build

  preview:
    aliases: [ "p" ]
    cmds:
      - bun run preview

  deploy:
    aliases: [ "dp", "up", "upload" ]
    cmds:
      - echo "deploy to {{ .GIT_REPO }} gh-pages"
      - rm -rf .git/
      - git init
      - git add -A
      - git commit -m 'deploy'
#      - |
#        cd ..;
#        repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git " '{print "git@github.com:"$1".git"}'`;
#        echo "git remote add $repo_url";
#        cd .dist/;
#        git remote add origin $repo_url
      - git remote add origin {{.GIT_REPO}}
      - git branch -M {{.BRANCH}}
      - git push -f origin {{.BRANCH}}
    dir: .vitepress/dist/
    vars:
      GIT_REPO: git@github.com:better-try/better-try.github.io.git
      BRANCH: gh-pages
    ignore_error: true

  quick:
    aliases: [ "q" ]
    cmds:
      - task: build
      - task: deploy
      - task: open

  clean:
    aliases: [ "cl", "rm" ]
    cmds:
      - rm -rf cache/
      - rm -rf dist/
    dir: .vitepress/


  echo:
    cmds:
      - echo "deploy to {{ .GIT_REPO }} gh-pages"
    vars:
      GIT_REPO: git@github.com:better-ts/vitepress-template.git

  fmt:
    aliases: [ "fmt-repo-url" ]
    cmds:
      - |
        repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git " '{print "git@github.com:"$1".git"}'`;
        echo $repo_url; 

  open:
    aliases: [ "open-repo-url" ]
    cmds:
      - echo $(git remote -v | grep push | awk -F ":" '{print $2}')
      - |
        repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git " '{print "https://github.com/"$1}'`;
        open $repo_url;