version: "3"

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing


################################################################################################

tasks:
  default:
    cmds:
      - echo "hello world"

  install:
    aliases: [ "i" ]
    cmds:
      - bun install

  add:
    aliases: [ "a" ]
    cmds:
      - bun add -D vitepress
      - bun add -D open-cli
      - bun add -D @lunariajs/core
      - bun add -D markdown-it-mathjax3
      - bun add -D naive-ui
      #      - bun add -D unocss
      #      - bun add -D @unocss/postcss
      - bun add -D daisyui@latest
      - bun add -D tailwindcss
      - bun add -D postcss
      - bun add -D prettier
      - bun add -D autoprefixer
      - bun add -D @iconify/vue # icon

  fix:quasar:
    aliases: [ "fq" ]
    cmds:
      - bun add quasar @quasar/extras
      - bun add --dev @quasar/vite-plugin sass@^1.33.0
      - bun add --dev unplugin-vue-components
      - bun add --dev unplugin-auto-import

  check:
    cmds:
      - quasar  -h
      - quasar info

  remove:
    aliases: [ "rm" ]
    cmds:
      - bun remove unocss
      - bun remove @unocss/postcss

  run:
    aliases: [ "r" ]
    cmds:
      - bun run dev

  build:
    aliases: [ "b" ]
    cmds:
      - bun run build
      - open ./.vitepress/dist/

  preview:
    aliases: [ "p" ]
    cmds:
      - bun run preview

  deploy:
    aliases: [ "dp", "up", "upload" ]
    cmds:
      - echo "deploy to {{ .GIT_REPO }} gh-pages"
      # TODO X: 删除 .git 文件
      - rm -rf .git/
      - git init
      # TODO X: 如果是发布到自定义域名
      - echo '{{ .DOMAIN }}' > CNAME
      - git add -A
      - git commit -m 'deploy'
      #      - |
      #        cd ..;
      #        repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git " '{print "git@github.com:"$1".git"}'`;
      #        echo "git remote add $repo_url";
      #        cd .dist/;
      #        git remote add origin $repo_url
      - git remote add origin {{.GIT_REPO}}
      - git branch -M {{.BRANCH}}
      - git push -f origin {{.BRANCH}}
    dir: .vitepress/dist/
    vars:
      GIT_REPO: git@github.com:better-try/better-try.github.io.git
      BRANCH: gh-pages
      DOMAIN: "trybetter.app"
    ignore_error: true

  quick:
    aliases: [ "q" ]
    cmds:
      - task: build
      - task: deploy
      - task: open

  clean:
    aliases: [ "cl" ]
    cmds:
      - rm -rf cache/
      - rm -rf dist/
    dir: .vitepress/


  echo:
    cmds:
      - echo "deploy to {{ .GIT_REPO }} gh-pages"
    vars:
      GIT_REPO: git@github.com:better-ts/vitepress-template.git

  fmt:
    aliases: [ "fmt-repo-url" ]
    cmds:
      - |
        repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git " '{print "git@github.com:"$1".git"}'`;
        echo $repo_url;

  open:
    aliases: [ "open-repo-url" ]
    cmds:
      - echo $(git remote -v | grep push | awk -F ":" '{print $2}')
      - |
        repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git " '{print "https://github.com/"$1}'`;
        open $repo_url;
